// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
let timeout = 0
// END EXTRA CODE

/**
 * @param {Nanoflow} parameter
 * @returns {Promise.<void>}
 */
export async function JS(parameter) {
	// BEGIN USER CODE
	if(interval != 0){
		timeout = setTimeout(function () {
			timeout = 0
		})
		await parameter()
	}
	
	// END USER CODE
}
